apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vaultwarden-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/assafdori/password-manager.git'
    path: 'kubernetes'
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
